### ISSUE TITLE
multicolumn footer menu

### ISSUE THREAD

**Issue by phish108** [dxiai/dxiai-theme#1]
Having multi-column footers. 

Either 1 (on mobile), 3 on tablets, 4 on desktops and 6 on wideschreen. 

The footer layout should be adaptive towards the number of total columns. Eg., if we have 5 columns, desktops should use a three column layout instead of a 4 column layout. Similarly, if we have 4 columns, tablets should use a 2 column layout. 

The yaml for the footer may look as follows:

```yaml
- title: abcd
  text: some longer text
  column:
  - name: xxx
     link: /

- title: abc 
  column:
  - name: yyy
     link: /yyy
```
